name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang-format valgrind

      - name: Build
        run: make all

      - name: Run tests
        run: make check

      - name: Check code formatting
        run: make format-check

      - name: Check copyright headers
        run: |
          go install github.com/google/addlicense@latest
          make copyright-check
        continue-on-error: true

  valgrind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and run Valgrind in Docker
        run: |
          docker build -t sstr-valgrind .
          docker run --rm sstr-valgrind
  
  # Optional MacOS build for cross-platform validation
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          brew install cmake
          
      - name: Build
        run: make all
        
      - name: Run tests
        run: make check