name: Valgrind Memory Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and run Valgrind in Docker
        run: |
          docker build -t sstr-valgrind .
          docker run --rm sstr-valgrind